USE [master]
GO

----------------------------------------------------------------------
-- Author: Christian Oleson
-- Course: MSI-505
-- Individual Project 1
----------------------------------------------------------------------
-- Create Shell Database
----------------------------------------------------------------------

CREATE DATABASE [MSI-505]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MSI-505', FILENAME = N'C:\DATA\MSI-505.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MSI-505_log', FILENAME = N'C:\MSI-505_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MSI-505].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MSI-505] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MSI-505] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MSI-505] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MSI-505] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MSI-505] SET ARITHABORT OFF 
GO

ALTER DATABASE [MSI-505] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MSI-505] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [MSI-505] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MSI-505] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MSI-505] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MSI-505] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MSI-505] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MSI-505] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MSI-505] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MSI-505] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MSI-505] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [MSI-505] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MSI-505] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MSI-505] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MSI-505] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MSI-505] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MSI-505] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MSI-505] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MSI-505] SET  MULTI_USER 
GO

ALTER DATABASE [MSI-505] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MSI-505] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MSI-505] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MSI-505] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MSI-505] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MSI-505] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MSI-505] SET QUERY_STORE = OFF
GO

USE [MSI-505]
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = ON;
GO

ALTER DATABASE [MSI-505] SET  READ_WRITE 
GO


